### ISSUE TITLE
Demo of tagFormat

### ISSUE THREAD

**Issue by Miniland1333** [mathjax/mj3-demos#14]
https://mathjax.github.io/mj3-demos/#tex-extensions
I'm attempting to use tagFormat as a replacement for equationNumbers from v2, but I haven't been able to figure out the syntax in the configuration using trial-and-error since I thought that the syntax would be somewhat similar to equationNumbers.

Other than this, my testing indicates that v3 will be a nice improvement for our application!

**Comment by Miniland1333** [comment]
```
MathJax = {
  tex: {
     macros: {
        test: ["{"+front+" #1}",1]
     },
     tags: "all",
     tagFormat: function (n) {
        return `Equation ${n}`;
     }
  }
};
```

**Comment by dpvc** [comment]
I think what you want is

```
MathJax = {
  tex: {
     packages: {'[+]': ['tagFormat']},   // add it to the default packages
     macros: {
        test: ["{"+front+" #1}",1]
     },
     tags: "all",
     tagFormat: {
        number: function (n) {
          return `Equation ${n}`;
       }
    }
  }
};
```

You can also specify `tag`, `id`, and `url` functions.  The defaults are:

```
    tagFormat: {
        number: (n) => n.toString(),
        tag:    (tag) => '(' + tag + ')',
        id:     (id) => 'mjx-eqn-' + id.replace(/\s/g, '_'),
        url:    (id, base) => base + '#' + encodeURIComponent(id),
    }
```

I hope that clears it up for you.

Sorry for not getting back to you sooner; I only just saw the message today (for some reason, I wasn't signed up to get automatic emails for this tracker!).

**Comment by Miniland1333** [comment]
From the console: _MathJax(?): Invalid option "tagFormat" (no default value)._

```javascript
MathJax = {
  tex: {
     packages: {"[+]": ["tagFormat"]},
     macros: {
        test: ["{"+front+" #1}",1]
     },
      tags: "all",
      tagFormat: {
          number: function (n) {
                    return `Equation ${n}`;
                   }
      }
  }
};
```

I think this is functionally equivalent to the code above, so I am not sure what is still incorrect. If it matters, I am using https://github.com/mathjax/mj3-demos/blob/master/mathjax3/tex-chtml.js as the javascript file since you had it precompiled for the demos and it seemed to be working just fine there. Maybe I have to specially compile in order to include tagFormat?

**Comment by dpvc** [comment]
This probably means you haven't loaded the `tagFormat` extension.  Try

```
MathJax = {
  loader: {
     load: ['[tex]/tagFormat']
  },
  tex: {
     packages: {"[+]": ["tagFormat"]},
     macros: {
        test: ["{"+front+" #1}",1]
     },
     tags: "all",
     tagFormat: {
         number: function (n) {
             return `Equation ${n}`;
         }
      }
  }
};
```

**Comment by Miniland1333** [comment]
Finally had a chance to test the loader and it worked! Do you think the documentation needs any updating to include this example of loading and using tagFormat?

**Comment by dpvc** [comment]
The documentation for v3 is still being written, and yes, `tagFormat` should be included in that.

**Comment by Miniland1333** [comment]
Thanks!
